language: python
python:
- 3.7
before_install:
- bash write_pip_config.sh
install:
- pip install -r dev-requirements.txt
script:
- bash docker.sh update_image --package-name=smartsegmentsml --package-version=2.0.5
        #- invoke test
deploy:
  provider: script
  script:
  - invoke deploy-jobs
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(dev|stage|master)$
env:
  global:
  # ARTIFACTORY_USERNAME
  - secure: TODO
  # AFTIFACTORY_PASSWORD
  - secure: TODO
