language: python

install:
- sudo apt-get update
- sudo apt install python3-dev
#- pip install -r requirements.txt

stages:
- name: test
  if: branch != master
- name: deploy
  if: branch = master AND type = push

jobs:
  include:
  - script: flake8 src
  - stage: test
    script:
    - sh hello.sh
